"""adiconando coluna desconto

Revision ID: 16ba91dd88fb
Revises: bc6048a60293
Create Date: 2024-01-24 23:16:10.717092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ba91dd88fb'
down_revision: Union[str, None] = 'bc6048a60293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('desconto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'desconto')
    # ### end Alembic commands ###
