"""relacionando Produto e Usuario

Revision ID: bdb10d00038d
Revises: 1c7d56e58878
Create Date: 2024-01-24 23:55:19.337378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb10d00038d'
down_revision: Union[str, None] = '1c7d56e58878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_usuario', 'produto', 'usuario', ['id_usuario'], ['id'])
    op.add_column('usuario', sa.Column('senha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'senha')
    op.drop_constraint('fk_usuario', 'produto', type_='foreignkey')
    op.drop_column('produto', 'id_usuario')
    # ### end Alembic commands ###
